[Wdp240301-8] - Użycie zmiennych do kolorów.
matwjablonski/wdp-2403-01 pull request #10
Opened 2024-02-22 19:21 UTC by basl3r

Link: https://projects.kodilla.com/browse/WDP240301-8

Zadanie:
Stworzenie zmiennych w pliku styli settings.scss i użycie ich w pozostałych plikach stylów.

Rozwiązanie:
Zgodnie z zadaniem stworzyłem zmienne i pogrupowałem je zgodnie z componentami dla większej czytelności. Wszystkie zmienne zostały już podmienione w plikach styli komponentów

Wszystko działa jak powinno.

2024-02-23 15:15 UTC, Br3mx submitted a review, later dismissed

2024-02-24 13:01 UTC, Br3mx submitted a review, later dismissed

2024-02-24 15:36 UTC, ufsowa submitted a review, later dismissed

2024-02-26 08:22 UTC, matwjablonski requested changes

2024-02-26 08:22 UTC, matwjablonski commented on src/styles/settings.scss
> +// ABOVE VARIABLES MUST NOT BE USED IN FILES, PLEASE USE THE BELOW
lepiej dać ten komentarz nad, będzie lepiej widoczny

2024-02-26 14:47 UTC, nietakbo approved these changes

2024-02-26 20:43 UTC, basl3r commented on src/styles/settings.scss
> +// ABOVE VARIABLES MUST NOT BE USED IN FILES, PLEASE USE THE BELOW
poprawione

2024-02-27 10:16 UTC, ufsowa submitted a review, later dismissed
Napraw konflikty i masz approva

2024-02-27 18:59 UTC, ufsowa approved these changes

2024-02-28 08:33 UTC, ufsowa approved these changes

2024-02-28 14:41 UTC, nietakbo approved these changes

2024-02-29 07:10 UTC, merged