WDP240301-7 add styles for select in product search menu
matwjablonski/wdp-2403-01 pull request #12
Opened 2024-02-23 15:26 UTC by nietakbo

ZADANIE: 
Select nie jest prawidłowo ostylowany:
-chyba zły rozmiar czcionki
-zostaje outline po zmianie kategorii
-brak hoverów
Do poprawy wedle designu. 

Od razu zaznacze ze dodanie funkcjonalności jest w kolejnym zadaniu, które zaraz zrobie :D

2024-02-24 12:55 UTC, Br3mx reviewed
![select](https://github.com/matwjablonski/wdp-2403-01/assets/145561870/3e175de1-38e5-44bf-9709-e13e3fd6ba85)

Te niebieskie tło takie brzydkie, nie pasuje moim zdaniem do strony, oraz ja bym nieco zmniejszył zaokrąglenie :)

2024-02-24 13:00 UTC, Br3mx approved these changes

2024-02-24 15:31 UTC, ufsowa requested changes

2024-02-24 15:31 UTC, ufsowa commented on src/components/features/ProductSearch/ProductSearch.module.scss
>      }
Jeszcze hover trzeba dodać aby select podswietlal się na hover.

2024-02-26 12:03 UTC, nietakbo commented on src/components/features/ProductSearch/ProductSearch.module.scss
>      }
ano tak, juz poprawiam :D

2024-02-26 17:25 UTC, ufsowa commented on src/components/features/ProductSearch/ProductSearch.module.scss
>      }
Ja bym proponował rozwiązać hovera w tym tasku, ponieważ WDP-10 może zostać zmergowany w innym momencie i będzie brzydko to wyglądało u klienta, jesli trzeba będzie nagle zademostrować mastera ;)

2024-02-26 17:27 UTC, ufsowa approved these changes

2024-02-27 08:09 UTC, merged