[WDP-20] Dodanie obslugi eventu window resize
matwjablonski/wdp-2403-01 pull request #14
Opened 2024-02-24 20:05 UTC by ufsowa

https://projects.kodilla.com/browse/WDP240301-20

Wykrywa zmiane window
Aktualizuje stora zmienna activeViewMode
Cała logika jest w viewModeReducerze.

Tylko strasznie spamuje eventami...?

Może przenieść logike do komponentu i wysyłac dispatch tylko jak sa spełnione warunki?

2024-02-24 21:33 UTC, ufsowa commented on src/redux/viewModeRedux.js
> +};
Czy przenieść do do utisów?

2024-02-24 23:30 UTC, ufsowa commented on src/redux/viewModeRedux.js
> +};
Przeniosłem

2024-02-25 04:34 UTC, Br3mx approved these changes

2024-02-26 08:25 UTC, matwjablonski approved these changes

2024-02-26 08:25 UTC, matwjablonski commented on package.json
> +    "redux-mock-store": "^1.5.4",
zgodnie z dobrymi praktykami do testów nie mocujemy store'a - tylko używamy jego realnej implementacji

2024-02-26 08:26 UTC, matwjablonski requested changes

2024-02-26 08:26 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.test.js
> +const store = mockStore({});
tak jak pisałem wcześniej, zaimportuj z pliku redux/store store i przekaż go do providera

2024-02-26 17:40 UTC, ufsowa commented on package.json
> +    "redux-mock-store": "^1.5.4",
lib usunięty

2024-02-26 17:40 UTC, ufsowa commented on src/components/features/NewFurniture/NewFurniture.test.js
> +const store = mockStore({});
mock store usunięty

2024-02-28 14:42 UTC, nietakbo approved these changes

2024-02-29 07:14 UTC, matwjablonski requested changes
nie widzę zastosowania dla redux-thunk, po co został dodany?

2024-02-29 14:38 UTC, ufsowa commented
redux-thunk został po pierwszej koncepcji, posprzątałem i usunąłem.

Poprawiłem stylownie RWD dla mebli oraz menu i dotsów.

2024-02-29 16:56 UTC, ufsowa commented
> Przy wersji na tablecie powinny się wyświetlać tylko 3 produkty new furniture, teraz wyświetla się 6. Dla komputerów i telefonów działa ekstra.
> 
> ![image](https://private-user-images.githubusercontent.com/66574995/309006661-fea3ec83-228b-4788-93d3-9b1151d5187a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjYwMjksIm5iZiI6MTcwOTIyNTcyOSwicGF0aCI6Ii82NjU3NDk5NS8zMDkwMDY2NjEtZmVhM2VjODMtMjI4Yi00Nzg4LTkzZDMtOWIxMTUxZDUxODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE2NTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWM3OTE2NDRkMDljZTQyMzQyYmZhMmFhYTFlMDgwNTAzODdmMjA3NjkzOGEyMTg1MWRlMWE3NTgzYThhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baUtU8Wl_5GpRxHTWIUb-73RHk6jQOxAUtD5NF0YjWc)

6 wygląda lepiej niż 3, zwłaszcza że jest na to miejsce

2024-02-29 17:15 UTC, basl3r commented
tylko, że w tickecie https://projects.kodilla.com/browse/WDP240301-17 klient prosi o 3

2024-02-29 17:17 UTC, basl3r submitted a review, later dismissed

2024-03-01 19:49 UTC, matwjablonski approved these changes

2024-03-01 19:53 UTC, matwjablonski requested changes

2024-03-01 19:53 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +  static getDerivedStateFromProps(props, current_state) {
zmienne w JS zapisujemy za pomocą jednej konwencji `camelCase`

2024-03-01 19:58 UTC, ufsowa commented on src/components/features/NewFurniture/NewFurniture.js
> +  static getDerivedStateFromProps(props, current_state) {
poprawione

2024-03-01 20:30 UTC, basl3r approved these changes

2024-03-01 21:21 UTC, nietakbo submitted a review, later dismissed
wygląda i działa super :D

2024-03-01 21:42 UTC, Br3mx submitted a review, later dismissed

2024-03-05 06:29 UTC, Br3mx approved these changes

2024-03-05 07:37 UTC, basl3r approved these changes

2024-03-06 01:14 UTC, merged