[WDP240301-17]: RWD - nowe meble
matwjablonski/wdp-2403-01 pull request #16
Opened 2024-02-26 20:38 UTC by basl3r

Link: https://projects.kodilla.com/browse/WDP240301-17

Zadanie:
Klient chciałby na tabletach mieć po 2-3 elementy w rzędzie, a na mobilkach 1-2 w rzędzie. Klient podał orientacyjne liczby elementów, bo trzeba będzie samodzielnie zdecydować co wygląda ok. Robimy tylko trzy warianty: desktop, tablet i mobile.

Docelowo na tabletach i mobilkach ma być tylko jeden rząd, a pozostałe dostępne za pomocą klikania w kropki paginacji (prawy górny róg tego komponentu), ale na to będzie osobne zadanie, na razie może się wyświetlać zawsze 8 produktów per strona.

Rozwiązanie:
Dostosowanie styli wyświetlania kolumn używając bootstrapa. Dodanie instrukcji warunkowych w zależności od stanów isMobile, isTablet, gdzie określony jest wielkość okna dla urządzeń mobilnych. Dodanie również stanu showAllProducts i napisanie funkcji do wyświetlania wszystkich produktów po podwójnym naciśnięciu na kropki paginacji.

Wszystko działa jak powinno.

2024-02-27 19:45 UTC, nietakbo commented
wygląda dobrze :D

2024-02-27 19:46 UTC, nietakbo approved these changes

2024-02-27 21:09 UTC, matwjablonski requested changes

2024-02-27 21:09 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +      isTablet: window.innerWidth > 768 && window.innerWidth <= 992, // New state to determine if the device is a tablet
komentarze są zbędne, już po nazwie widać co to jest ;)

2024-02-27 21:09 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +  // New function used to toggle all products
tak samo tutaj, dodawanie komentarza który mówi co robi funkcja nic nie wnosi, sama jej nazwa powinna już być wystarczająco opisowa

2024-02-27 21:22 UTC, basl3r commented on src/components/features/NewFurniture/NewFurniture.js
> +  // New function used to toggle all products
Poprawione.

2024-02-28 19:39 UTC, nietakbo approved these changes

2024-02-29 07:14 UTC, matwjablonski approved these changes

2024-02-29 07:14 UTC, merged