{Wdp 240301 12}
matwjablonski/wdp-2403-01 pull request #18
Opened 2024-02-27 22:06 UTC by Br3mx

Link: https://projects.kodilla.com/browse/WDP240301-12

**POTRZEBUJĘ POMOCY**
1. Nie wiem dlaczego ale w ProductBoxie jak widać musiałem wyłączyć useDistpatch ( znakami /* */ ), ponieważ testy mi nie wychodzą nie wiem dlaczego i nie mogłem zaccomitować zmian aby zrobić pusha, mimo że funkcja działa.
2. Nie wiem jak poprawnie podlinkować src do obrazów, products.category i products.id pokazuje mi undefined.

**Prośba**
Jeśli ktoś ma jakiś pomysł aby to rozwiązać prosiłbym o pomoc.

2024-02-27 23:35 UTC, ufsowa requested changes

2024-02-27 23:35 UTC, ufsowa commented on src/components/views/CompareProducts/CompareProducts.js
> +  };
nie do konca rozumiem co ten kod robi? Po kliknieciu compare usuwa z listy compare?

2024-02-27 23:35 UTC, ufsowa commented on src/components/views/CompareProducts/CompareProducts.js
> +              src={`${process.env.PUBLIC_URL}/images/products/${products.category}/${products.id}.jpg`}
nie zapisujesz takich pul w storze jak category lub id.

Zapisujesz tylko nazwy w dispatchu.

2024-02-27 23:35 UTC, ufsowa commented on src/components/common/ProductBox/ProductBox.js
> +  const product = { name };
tutaj zapisujesz do stora compare name,

a pozniej chcesz obrazek dla category oraz id.
Nie ma tych informacji w storze compare, dlatego masz undefina.

2024-02-27 23:35 UTC, ufsowa commented on src/components/common/ProductBox/ProductBox.js
> +  const product = { name };
najlepiej zapisuj id do compare.

Nastepnie przy porownania pobierz caly product o takim id.
Do tego trzeb napisa selector: getProductById 
wtedy bedziesz mial wszystkie dane

2024-02-29 14:52 UTC, ufsowa submitted a review, later dismissed

2024-02-29 16:27 UTC, basl3r submitted a review, later dismissed

2024-02-29 16:32 UTC, basl3r commented on src/components/views/CompareProducts/CompareProducts.module.scss
> +  color: $primary;
Nie skompiluje Ci się, jako, że nie ma już zmiennej primary. 

Zmerguje maina do brancha i użyj prawidłowej zmiennej dla koloru. Jak jej nie ma to stwórz.

2024-02-29 16:54 UTC, basl3r approved these changes

2024-03-01 19:58 UTC, matwjablonski requested changes
<img width="1218" alt="Zrzut ekranu 2024-03-1 o 20 56 50" src="https://github.com/matwjablonski/wdp-2403-01/assets/20933197/05f588df-95b4-41df-9923-69db57a16678">

wygląda to źle. produkty są nierówne. dodatkowo nie jest to sticky bar, który był opisany w zadaniu. sticky bar polega na tym, że jest on przyczepiony do krawędzi ekranu lub elementu i podąża za użytkownikiem

2024-03-01 19:58 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +.compare {
linia przerwy

2024-03-01 21:51 UTC, Br3mx commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +.compare {
już poprawiam

2024-03-01 22:33 UTC, ufsowa commented on src/components/views/CompareProducts/CompareProducts.module.scss
> +  background-color: $grayTwo;
można dac półprzezroczysty background

2024-03-01 22:33 UTC, ufsowa commented on src/components/views/CompareProducts/CompareProducts.module.scss
> +  display: flex;
na RWD sie rozwala.
można dać flex-wrap

2024-03-01 22:39 UTC, Br3mx commented on src/components/views/CompareProducts/CompareProducts.module.scss
> +  background-color: $grayTwo;
Jak ustawie przeźroczyste tło to zdjęcia będą brzydko nachodzić na inne produkty, bo się to przesuwa wraz ze scrollem strony
position sticky

2024-03-04 07:51 UTC, ufsowa approved these changes

2024-03-04 16:36 UTC, nietakbo approved these changes

2024-03-05 13:10 UTC, ufsowa approved these changes

2024-03-05 13:41 UTC, nietakbo submitted a review, later dismissed

2024-03-06 15:57 UTC, gitmaciejpiotr submitted a review, later dismissed

2024-03-06 16:58 UTC, basl3r submitted a review, later dismissed

2024-03-06 17:05 UTC, ufsowa approved these changes

2024-03-07 11:35 UTC, matwjablonski submitted a review, later dismissed
<img width="1267" alt="Zrzut ekranu 2024-03-7 o 12 34 22" src="https://github.com/matwjablonski/wdp-2403-01/assets/20933197/381fce3f-af5f-4feb-9af2-e859f848609b">

to tak nie może wyglądać, jak dodasz 4 to zajmuje cały ekran i nie widać nic pod spodem. poza tym powinny być 4 obok siebie.

2024-03-07 14:29 UTC, ufsowa submitted a review, later dismissed

2024-03-08 15:55 UTC, ufsowa commented
Dobrze byłoby tutaj dodać RWD bo ma mobile nie mieszczą się 4 elementy.
Warto by zmniejszyć do 2 elementów max

2024-03-08 20:25 UTC, ufsowa submitted a review, later dismissed

2024-03-11 20:59 UTC, ufsowa approved these changes

2024-03-12 17:13 UTC, nietakbo approved these changes

2024-03-12 19:57 UTC, merged