Add RWD styles to top menu bar
matwjablonski/wdp-2403-01 pull request #21
Opened 2024-03-01 17:33 UTC by gitmaciejpiotr

Strona sypie się w trybach responsive. Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 

Ten task dotyczy menu głównego (wyszukiwanie i "Home", etc.) 

Na tabletach wyszukiwanie ma być pod menu, a na mniejszych ekranach ma być wyszukiwanie i obok niego ikona mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony.

2024-03-02 08:10 UTC, ufsowa commented
Można jakoś wyróżnic hamburgera, teraz jest mało widoczny
![image](https://github.com/matwjablonski/wdp-2403-01/assets/21135760/447a0a1e-368d-45b2-9fe0-dacf7ae1d551)

2024-03-02 08:25 UTC, ufsowa commented on .gitignore.bak
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
Ten plik jest nie potrzebny, usuń

2024-03-02 08:25 UTC, ufsowa commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +   height: 60px;
wcięcia

2024-03-02 08:25 UTC, ufsowa commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    border-bottom: 1px solid $form-border-color;
wcięcia

2024-03-02 13:53 UTC, gitmaciejpiotr commented
Poprawki naniesione, moim zdaniem jest ok.

2024-03-04 07:50 UTC, ufsowa submitted a review, later dismissed

2024-03-04 16:38 UTC, nietakbo submitted a review, later dismissed

2024-03-04 16:40 UTC, basl3r submitted a review, later dismissed

2024-03-06 17:08 UTC, ufsowa approved these changes

2024-03-06 17:18 UTC, basl3r approved these changes

2024-03-07 12:52 UTC, matwjablonski requested changes

2024-03-07 14:32 UTC, gitmaciejpiotr commented on package.json
> +    "react-bootstrap": "^2.10.1",
Nie ustalałem tego. Myślałem, że możemy korzystać z zasobów, które omawialiśmy w trakcie kursu. Co z tym powinienem zrobić?

2024-03-07 16:45 UTC, matwjablonski commented on package.json
> +    "react-bootstrap": "^2.10.1",
Możesz, ale to jest decyzja, która wpłynie mocno na wydajność strony. W projekcie był bootstrap i jeszcze teraz jest kolejny framework UI - wg mnie można to napisać bez tej biblioteki - lub dogadaj z zespołem co myślą i jeśli wszyscy się zgodzą to może to zostać.

2024-03-07 16:46 UTC, matwjablonski commented on package.json
> +    "bootstrap": "^4.6.2",
jeśli podbiłeś to sprawdź czy czasem czegoś nie wysypałeś i wtedy niech zostanie.

2024-03-08 12:03 UTC, matwjablonski approved these changes

2024-03-08 12:03 UTC, merged