Wdp240301 30 - Brand slider bez funckjonalności
matwjablonski/wdp-2403-01 pull request #22
Opened 2024-03-02 12:42 UTC by Br3mx

Link: https://projects.kodilla.com/browse/WDP240301-30

**Zadanie**
Dodanie brand slideru bez funkcjonalności, pobieranie danych ze stanu

2024-03-02 14:55 UTC, gitmaciejpiotr requested changes
Trochę naspamiłem, mam nadzieję, że pożytecznie.
Nie ma responsive na tym sliderze. Wydaje mi się, że trzeba dodać.
Pozdrówki

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +  border-bottom: 0.06rem solid $grayTwo;
Dałbym 0.08rem i $lighterGrayTwo - moim zdaniem wtedy bardziej przypomina to co layoucie.

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +    border: 0.06rem solid $grayTwo;
Dałbym 0.08rem i $lighterGrayTwo - moim zdaniem wtedy bardziej przypomina to co layoucie.

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +    height: 7.2rem;
Dałbym 5.4rem

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +  height: 8rem;
Dałbym 8.8rem

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +    height: 80%;
Dałbym 5.4rem

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +    width: 80%;
Dałbym 10rem

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +    width: 7rem;
Dałbym 2rem

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +
Dodałbym:
 margin-right: 1rem;

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +      color: $white;
Dodałbym:
font-size: 12px;

2024-03-02 14:55 UTC, gitmaciejpiotr commented on src/components/views/Brands/Brands.module.scss
> +    }
Dodałbym:
button:nth-of-type(2){
    margin: 0;
    margin-left: 1rem;
  }

2024-03-02 15:12 UTC, Br3mx commented
Na rwd jest osobne zadanie

2024-03-02 16:59 UTC, gitmaciejpiotr approved these changes

2024-03-04 16:28 UTC, basl3r approved these changes

2024-03-05 00:40 UTC, ufsowa approved these changes

2024-03-05 13:48 UTC, nietakbo approved these changes

2024-03-06 15:58 UTC, gitmaciejpiotr approved these changes

2024-03-06 17:30 UTC, basl3r approved these changes

2024-03-06 17:36 UTC, ufsowa approved these changes

2024-03-07 12:52 UTC, merged