[WDP240301-6] Dodanie starej ceny produktu
matwjablonski/wdp-2403-01 pull request #3
Opened 2024-02-21 21:44 UTC by ufsowa

Link: https://projects.kodilla.com/browse/WDP240301-6 

**Task**:
Na karcie produktu ma być możliwość wyświetlenia starej ceny, która ma być przekreślona. 
Tylko przy niektórych produktach będzie stara cena. 

**Solution:**
Wizualnie wyświtla się stara cena pobrana ze stora.

**Comments:**
Zastanawiam się czy ujednolicić 'price' i mieć wszystko w jednym miejscu, czy może jako Button, choć dziwny to byłby Button?
Może kolejny task - generalnie fajnie byłoby aby styl price był w jedny miejscu. Teraz price jest stylowane w dwóch różnych komponentach: Button i ProductBox.

2024-02-21 22:36 UTC, Br3mx submitted a review, later dismissed

2024-02-22 08:03 UTC, matwjablonski requested changes
w zasadzie zamiast tworzyć nowe zadanie można refaktoryzację zrobić tutaj. cenę możesz wydzielić do osobnego komponentu i wówczas wszystko będzie w jednym miejscu

2024-02-22 11:35 UTC, ufsowa commented
Dodałem nowy komponent Price

2024-02-22 15:06 UTC, Br3mx submitted a review, later dismissed

2024-02-22 18:07 UTC, nietakbo approved these changes

2024-02-22 19:24 UTC, matwjablonski requested changes

2024-02-22 19:24 UTC, matwjablonski commented on src/components/common/Price/Price.js
> +  if (!price || price < 0) return <></>;
`return null` zamiast takiego pustego ReactNode

2024-02-22 19:24 UTC, matwjablonski commented on src/components/common/Price/Price.module.scss
> +    background-color: #2a2a2a;
kolory do zmiennych poproszę

2024-02-22 19:24 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +    .price {
te style są jeszcze potrzebne skoro przeniosłeś kod do osobnego komponentu?

2024-02-24 14:27 UTC, ufsowa commented on src/components/common/Price/Price.module.scss
> +    background-color: #2a2a2a;
ok

2024-02-24 14:28 UTC, ufsowa commented on src/components/common/ProductBox/ProductBox.module.scss
> +    .price {
tak, .price styluje boxy Price jako flex.
Natomiast reszte usuwam

2024-02-27 12:22 UTC, basl3r commented on src/redux/initialState.js
W paru miejscach, originalPrice ma wartosc undefined. Czy to jest zamierzony zabieg w wypadku kiedy stara cena jest taka sama jak aktualna?

2024-02-27 12:57 UTC, ufsowa commented on src/redux/initialState.js
Tak stara cena jest nie zdefiniowana i nie powinna być wyświetlana ;)

2024-02-27 12:59 UTC, basl3r approved these changes

2024-02-27 20:57 UTC, matwjablonski approved these changes

2024-02-27 20:57 UTC, merged