[WDP-2403-09] Stworzenie zmiennych dla animacji tła/tekstu/ikony
matwjablonski/wdp-2403-01 pull request #5
Opened 2024-02-22 12:49 UTC by Br3mx

Link: https://projects.kodilla.com/browse/WDP240301-9

**ZADANIE**
Polegało na napisaniu zmiennych do czasu animacji dla tekstu, tła i ikony.
**Info dla was**
Możecie zauważyć że są 3 różne wariancje time-animation osobno dla ikony tekstu i bakcground-coloru, mimo że mają takie same wartości. Zrobiłem tak ponieważ **Klient** rzekomo chciałby poeskpeymentować i mógłby chcieć zmienić czas animacji tylko dla wybranych elementów takich jak ikona itd, nie zmieniając przy tym czasu animacji w innych elementach.

Jeśli są jakieś uwagi do wartości zmiennych np do klasy move-hover proszę o info a zmienie :)

2024-02-23 08:17 UTC, Br3mx commented on src/styles/settings.scss
> +.move-hover {
Myślałem że chodzi tylko i wyłącznie o zapisanie zmiennych, jak wrócę do domu mogę je wykorzystać w komponentach

2024-02-23 18:03 UTC, ufsowa commented on src/styles/settings.scss
> +.move-hover {
Wydaje mi się że trzeb to wykorzystać ;)
Dodatkowo najlepiej zrobić za pomocą placeholdera %defaultHover i extenda w modulach

Opis:
Klient chce, żeby wszystkie efekty hover na guzikach itd. (wszędzie gdzie na hover zmienia się kolor tła, tekstu lub ikon, etc.) były animowane i takie same dla wszystkich elementów. Co więcej, będzie chciał łatwo zmieniać czasy tych animacji (globalnie dla wszystkich elementów). Może potrzebować, żeby czas animacji koloru tła i czas animacji koloru tekstu/ikony były różne. 

Klient chciałby poeksperymentować z efektami hover (nie tylko czasy animacji, ale też co się animuje, albo że np. hoverowany element będzie się lekko przesuwał), więc najlepiej zrobić to przez placeholder w settingsach, który będzie extendowany w każdym hoverowalnym elemencie.

Wstępnie ustawiamy czasy animacji na 250ms.

2024-02-23 18:03 UTC, ufsowa commented on src/styles/settings.scss
> +.move-hover {
Nie ma dużo, search "hover" wskazuje na 2-3 komponenty?

2024-02-24 15:20 UTC, ufsowa commented
Zmiana w porządku. Trzeba teraz konflikty rozwiązać

2024-02-24 16:17 UTC, ufsowa approved these changes

2024-02-26 08:12 UTC, matwjablonski requested changes
MenuBar nie jest animowane, a na hover też zmieniamy tło

2024-02-26 12:07 UTC, Br3mx commented
@matwjablonski zrobione

2024-02-26 14:57 UTC, nietakbo approved these changes

2024-02-26 22:27 UTC, ufsowa approved these changes

2024-02-27 07:03 UTC, matwjablonski approved these changes

2024-02-27 07:03 UTC, merged