[WDP-240301-15] RWD dla TopBaru i Baneru
matwjablonski/wdp-2403-01 pull request #6
Opened 2024-02-22 14:49 UTC by Br3mx

Link: https://projects.kodilla.com/browse/WDP240301-15

**Zadanie**
Dodanie RWD na mobilki dla TopBaru i Baneru _(Komponenty CompanyClaim)_.

Jeśli macie jakieś wątpliwości co do tego zadania to śmiało pytać, krytykę też przyjmę i naprawie ewentualne błędy ;)

2024-02-24 15:49 UTC, ufsowa commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +      {/*Mobile */}
Nie wgłębiałem się w taska za bardzo, ale wydaje mi się że może dałoby się to tak zrobić żeby nie rozróżniać w js czy to jest mobile czy desktop?

Czy nie da sie tego schować w scss za pomocą odpowiednich justify left right albo flex order??

Chodzi o to aby zamienić miejscami ikone.

2024-02-24 16:04 UTC, Br3mx commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +      {/*Mobile */}
Może i masz racje, ja osobiście zostawiłbym ten kod, ale jeśli robiłby on jakieś problemy to mogę to spróbować poprawić.
A inni jak myślą ? @matwjablonski @basl3r @gitmaciejpiotr  @nietakbo.

2024-02-27 11:55 UTC, basl3r approved these changes

2024-02-27 11:55 UTC, basl3r commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +      {/*Mobile */}
Ja bym to zostawił tak jak jest na razie.

2024-02-27 18:22 UTC, Br3mx commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +      {/*Mobile */}
Też tak myślę

2024-02-27 19:35 UTC, nietakbo submitted a review, later dismissed

2024-02-27 21:04 UTC, matwjablonski requested changes

2024-02-27 21:04 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +      {/*Mobile */}
wg mnie to jest duplikacja kodu i ja bym to wywalił - ewentualnie podzielił na komponenty lub przekazał przez kompozycję odpowiednie struktury, szczególnie te powtarzające się

np. dla część koszyka:


```jsx
const cart = <div className={`col text-right ${styles.cart}`}>
          <a href='#' className={styles.cartBox}>
            <div className={styles.cartIcon}>
              <FontAwesomeIcon className={styles.icon} icon={faShoppingBasket} />
            </div>
            <div className={styles.cartCounter}>0</div>
          </a>
        </div>
```
        
        
w kodzie to można później użyć: `{cart}`

i wywal proszę komentarze - są zbędne

2024-02-27 21:04 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +      img {
linie wolne pomiędzy regułami, gdy ostatnie są właściwości a nie selektor

2024-02-29 16:41 UTC, basl3r submitted a review, later dismissed

2024-03-01 19:48 UTC, matwjablonski requested changes
nie wszystkie poprzednie uwagi są wprowadzone

2024-03-01 19:48 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +            <a href='#'>
tutaj tez masz logo, po to przeniosłeś do zmiennych ten JSX żeby nie powielać kodu, teraz taka konstrukcja nie za bardzo ma sens. przeorganizuj to tak żeby nie było powielających się fragmentów kodu

2024-03-01 21:19 UTC, nietakbo submitted a review, later dismissed

2024-03-02 08:33 UTC, ufsowa commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +    .desktop {
odstepy

2024-03-02 15:20 UTC, gitmaciejpiotr approved these changes

2024-03-04 07:53 UTC, ufsowa approved these changes

2024-03-04 19:20 UTC, merged