Wdp240301 1
matwjablonski/wdp-2403-01 pull request #7
Opened 2024-02-22 16:39 UTC by basl3r

**Link:** https://projects.kodilla.com/browse/WDP240301-1

**Zadanie:**
Klient poprosił o dodanie przykładowych zdjęć na stronę główną

**Rozwiązanie:**
Pobrałem przykładowe obrazy i utworzyłem dla nich odpowiedni folder w folderze public. Stworzyłem nowy komponent ProductImage, który ładuję i renderuje zdjęcia z w/w folderu. Wykorzystałem ten komponent w ProductBox. 

Wszystko działa jak powinno.

2024-02-22 18:38 UTC, ufsowa submitted a review, later dismissed
Komentarz pod rozwagę, ale generalnie approve.

2024-02-22 18:38 UTC, ufsowa commented on src/components/common/ProductImage/ProductImage.js
> +        src={`${process.env.PUBLIC_URL}/images/products/beds/${id}.jpg`}
Jedynie możnaby ise zastanowić czy ta ścieżka mogłaby być zapisana w store pod nowym polem: path.
Wtedy ProductImage komponent mógłby być bardziej generyczny i słuzyć dla innych kategorii produktów.

Ale to można zrobic później aby nie blokować innych tasków.

2024-02-22 19:30 UTC, matwjablonski commented on src/components/common/ProductImage/ProductImage.js
> +        src={`${process.env.PUBLIC_URL}/images/products/beds/${id}.jpg`}
id idzie ze store'a, ale kategoria też mogłaby iść - w zasadzie masz rację - ale bym to poprawił od razu

2024-02-22 19:31 UTC, matwjablonski requested changes
popraw proszę komponent ProductImage tak żeby można go było przypisać do różnych kategorii

2024-02-22 19:32 UTC, Br3mx approved these changes

2024-02-22 19:43 UTC, basl3r commented
ProductImage przyjmuje też category i jest ona wykorzystane w sciezce do plikow.

2024-02-23 09:09 UTC, Br3mx approved these changes

2024-02-23 18:08 UTC, ufsowa submitted a review, later dismissed

2024-02-24 15:04 UTC, ufsowa commented
Trzeba rozwiązać konflikty.

2024-02-24 15:21 UTC, basl3r commented
Konflikty zostały rozwiązane.

2024-02-24 15:26 UTC, ufsowa approved these changes

2024-02-24 15:27 UTC, Br3mx approved these changes

2024-02-26 08:13 UTC, matwjablonski approved these changes

2024-02-26 08:13 UTC, merged