WDP2403001 editing buttons display - quick view and add to cart
matwjablonski/wdp-2403-01 pull request #8
Opened 2024-02-22 18:05 UTC by nietakbo

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=232&projectKey=WDP240301&view=detail&selectedIssue=WDP240301-4

Buttony "Quick view" oraz "Add to cart" powinny być widoczne tylko na hover całego boksa z produktem. Wtedy też powinno zmieniać się tło ceny.

2024-02-22 23:23 UTC, ufsowa reviewed
Fajna zmiana, można się jedynie zastanowić nad dodanie specialnego stylu onHover, który można dodawać lub usuwać w className.

Wtedy zapis byłby bardziej jednolity.

2024-02-23 18:09 UTC, ufsowa approved these changes

2024-02-24 13:03 UTC, Br3mx approved these changes

2024-02-24 15:40 UTC, ufsowa approved these changes

2024-02-26 08:19 UTC, matwjablonski requested changes

2024-02-26 08:19 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +          style={isHovered === true ? { opacity: 1 } : { opacity: 0 }}
dla mnie to za dużo, o wiele prościej jest użyć :hover z css'a

2024-02-26 08:19 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +          style={isHovered === true ? { opacity: 1 } : { opacity: 0 }}
poza tym inline styles to zła praktyka - łatwo zgubić później taką zmianę css'ową przy debugowaniu i ona ma bardzo wysoką specyficzność - trudno byłoby to nadpisać.

2024-02-26 08:19 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +            <FontAwesomeIcon icon={faShoppingBasket}></FontAwesomeIcon> ADD TO CART
```jsx
<FontAwesomeIcon icon={faShoppingBasket} /> ADD TO CART
```

2024-02-26 08:19 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +      transition: opacity 0.3s;
czas animacji weź proszę ze zmiennych

2024-03-01 21:13 UTC, closed without merging