Change styles of number of items in cart display
matwjablonski/wdp-2403-01 pull request #9
Opened 2024-02-22 18:20 UTC by gitmaciejpiotr

2024-02-24 16:13 UTC, ufsowa commented
Ustaw wartość na 9999 i spróbuj to wtedy ostylować tak aby liczba nie nachodziła na obrazek:

![image](https://github.com/matwjablonski/wdp-2403-01/assets/21135760/11f1e5b9-698f-45cb-b70d-398c8ac10d4d)

2024-02-24 16:16 UTC, ufsowa requested changes

2024-02-24 16:16 UTC, ufsowa commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +              <div className={styles.itemsAmount}>0</div>
ustaw na 99999

2024-02-26 08:20 UTC, matwjablonski requested changes
na mobile się to źle zachowuje, liczba wykracza poza granicę stronę

2024-02-26 08:20 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +              <div className={styles.itemsAmount}>0</div>
nie ma potrzeby takiej

2024-02-27 13:11 UTC, basl3r reviewed
Rozwiąż konflikty i będzie można mergować.

2024-03-01 22:36 UTC, ufsowa approved these changes

2024-03-04 16:33 UTC, nietakbo approved these changes

2024-03-05 15:09 UTC, basl3r submitted a review, later dismissed

2024-03-05 15:10 UTC, ufsowa reviewed
![image](https://github.com/matwjablonski/wdp-2403-01/assets/21135760/88e2e3b5-a93f-4666-bd9a-ac1b2d429545)

Masz jaki blad. Sprobuj odplaic projekt i napraw co tam sie wysypuje.

Mas tam nie potrzebny  na koncu---->    }
Propsa tez mozesz usunac
 
yarn start

2024-03-06 01:25 UTC, ufsowa approved these changes

2024-03-06 16:57 UTC, basl3r approved these changes

2024-03-06 18:30 UTC, nietakbo approved these changes

2024-03-07 11:32 UTC, matwjablonski approved these changes

2024-03-07 11:32 UTC, merged